AWSTemplateFormatVersion: 2010-09-09
Description: EC2 and RDS

Parameters:

#==========================================
# DBパラメータ
#==========================================
  DBName:
    Type: String
    Default: db

  DBMasterUserName:
    Type: String
    Default: dbuser

  DBPassword:
    Type: String
    Default: dbpassword


Resources: 

#==========================================
# DBサブネットグループの作成
#==========================================
  rdsDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: rdsDBSubnetGroup
      SubnetIds:
        - !ImportValue myVPC-PrivateSubnet01a
        - !ImportValue myVPC-PrivateSubnet01c
      Tags:
        - Key: Name
          Value: rdsDBSubnetGroup

#==========================================
# DBセキュリティグループ
#==========================================
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      # GroupName: 
      GroupDescription: SecurityGroup for RDS
      # VpcId:
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 10.0.1.0/24
      # SecurityGroupEgress:
      #   - Security Group Rule
      Tags:
        - Key: Name
          Value: RDSSecuriryGroup

# #==========================================
# # DBの作成
# #==========================================
  rdsDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t2.micro
      AllowMajorVersionUpgrade: true
      AutoMinorVersionUpgrade: true
      AvailabilityZone: ap-northeast-1a
      # BackupRetentionPeriod: 
      # CharacterSetName: 
      DBInstanceIdentifier: MyDB
      DBName: !Ref DBName
      # DBParameterGroupName: 
      # DBSecurityGroups: 
      #   - !Ref RDSSecurityGroup
      # DBSnapshotIdentifier: 
      DBSubnetGroupName: !Ref rdsDBSubnetGroup
      Engine: mysql
      # EngineVersion: 
      # Iops: 
      # KmsKeyId: 
      # LicenseModel: 
      MasterUsername: !Ref DBMasterUserName
      MasterUserPassword: !Ref DBPassword
      MultiAZ: false
      # OptionGroupName: 
      # Port: 
      # PreferredBackupWindow: 
      # PreferredMaintenanceWindow: 
      # PubliclyAccessible: true|false
      # SourceDBInstanceIdentifier: 
      # StorageEncrypted: true|false
      StorageType: gp2
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      Tags:
        - Key: Name
          Value: MyDB