AWSTemplateFormatVersion: 2010-09-09
Description: EC2 and RDS

Parameters:
#==========================================
# EC2パラメータ
#==========================================
  Ec2ImageId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

  Ec2InstanceType:
    Type: String
    Default: t2.micro

  KeyName:
    Description: The EC2 Key Pair to allow SSH access to the instance
    Type: "AWS::EC2::KeyPair::KeyName"

  MyIp:
    Description: IP address allowed to access EC2
    Type: String
    Default: 0.0.0.0/32

#==========================================
# DBパラメータ
#==========================================
  DBName:
    Type: String
    Default: db

  DBMasterUserName:
    Type: String
    Default: dbuser

  DBPassword:
    Type: String
    Default: dbpassword

Resources: 

#==========================================
# EC2セキュリティグループの作成
#==========================================
  WebServerSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      # GroupName: WebServer
      GroupDescription: http,https
      VpcId: !ImportValue myVPC
      SecurityGroupIngress:
        -
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        -
          IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        -
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MyIp
      # SecurityGroupEgress:
      #   - Security Group Rule
      Tags:
        - Key: Name
          Value: WebServerSg

#==========================================
# EC2インスタンスの作成
#==========================================
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      SubnetId: !ImportValue myVPC-PublicSubnet01a
      KeyName: !Ref KeyName
      DisableApiTermination: false
      ImageId: !Ref Ec2ImageId
      InstanceType: !Ref Ec2InstanceType
      SecurityGroupIds:
        - !Ref WebServerSg
      UserData: !Base64 |
        #!/bin/bash -ex
        sudo yum update -y
        sudo yum install -y httpd
        sudo systemctl enable httpd
        sudo systemctl start httpd
      Tags:
        - Key: Name
          Value: WebServer

  # WebServerSgIngress:
  #   Type: AWS::EC2::SecurityGroupIngress
  #   IpProtocol: tcp
  #   FromPort: 80
  #   ToPort: 80
  #   # CidrIp: 0.0.0.0/0

#==========================================
# DBサブネットグループの作成
#==========================================
  rdsDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: rdsDBSubnetGroup
      SubnetIds:
        - !ImportValue myVPC-PrivateSubnet01a
        - !ImportValue myVPC-PrivateSubnet01c
      Tags:
        - Key: Name
          Value: rdsDBSubnetGroup

#==========================================
# DBセキュリティグループ
#==========================================
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      # GroupName: 
      GroupDescription: SecurityGroup for RDS
      VpcId: !ImportValue myVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref WebServerSg
      # SecurityGroupEgress:
      #   - Security Group Rule
      Tags:
        - Key: Name
          Value: RDS-sg

#==========================================
# DBの作成
#==========================================
  rdsDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t2.micro
      AllowMajorVersionUpgrade: true
      AutoMinorVersionUpgrade: true
      AvailabilityZone: ap-northeast-1a
      # BackupRetentionPeriod: 
      # CharacterSetName: 
      DBInstanceIdentifier: MyDB
      DBName: !Ref DBName
      # DBParameterGroupName: 
      # DBSecurityGroups: 
      #   - !Ref RDSSecurityGroup
      # DBSnapshotIdentifier: 
      DBSubnetGroupName: !Ref rdsDBSubnetGroup
      Engine: mysql
      # EngineVersion: 
      # Iops: 
      # KmsKeyId: 
      # LicenseModel: 
      MasterUsername: !Ref DBMasterUserName
      MasterUserPassword: !Ref DBPassword
      MultiAZ: false
      # OptionGroupName: 
      # Port: 
      # PreferredBackupWindow: 
      # PreferredMaintenanceWindow: 
      # PubliclyAccessible: true|false
      # SourceDBInstanceIdentifier: 
      # StorageEncrypted: true|false
      StorageType: gp2
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      Tags:
        - Key: Name
          Value: MyDB