AWSTemplateFormatVersion: 2010-09-09
Description: JenkinsRole Create
Resources: 
  JenkinsIamRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: JenkinsEC2andCloudFormationFullAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'ec2:*'
                Resource: '*'
              
              - Effect: Allow
                Action: 'elasticloadbalancing:*'
                Resource: '*'
              
              - Effect: Allow
                Action: 'cloudwatch:*'
                Resource: '*'
              
              - Effect: Allow
                Action: 'autoscaling:*'
                Resource: '*'
              
              - Effect: Allow
                Action: 'iam:CreateServiceLinkedRole'
                Resource: '*'
              
              - Effect: Allow
                Action: 'cloudformation:*'
                Resource: '*'

                Condition:
                  StringEquals:
                    iam:AWSServiceName:
                      - "autoscaling.amazonaws.com"
                      - "ec2scheduled.amazonaws.com"
                      - "elasticloadbalancing.amazonaws.com"
                      - "spot.amazonaws.com"
                      - "spotfleet.amazonaws.com"
                      - "transitgateway.amazonaws.com"

  JenkinsInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref JenkinsIamRole

      # Policies:
      #   - PolicyName: EC2FullAccess
      #     Roles:
      #       - !Ref JenkinsIamRole
      #     PolicyDocument:
      #       Version: "2012-10-17"
      #       Statement:
      #         - 
      #           Effect: "Allow"
      #           Action: "ec2:*"
      #           Resource: "*"
      #         -
      #           Effect: "Allow"
      #           Action: "elasticloadbalancing:*"
      #           Resource: "*"
      #         -
      #           Effect: "Allow"
      #           Action: "cloudwatch:*"
      #           Resource: "*"
      #         -
      #           Effect: "Allow"
      #           Action: "autoscaling:*"
      #           Resource: "*"
      #         -
      #           Effect: "Allow"
      #           Action: "iam:CreateServiceLinkedRole"
      #           Resource: "*"
                # Condition:
                #   StringEquals:
                #     iam:AWSServiceName:
                #       - "autoscaling.amazonaws.com"
                #       - "ec2scheduled.amazonaws.com"
                #       - "elasticloadbalancing.amazonaws.com"
                #       - "spot.amazonaws.com"
                #       - "spotfleet.amazonaws.com"
                #       - "transitgateway.amazonaws.com"